name: Deploy to Server
on: [push]

jobs:
  # Job 1. Deploy to Server
  deploy_to_server:
    runs-on: macos-latest
    name: Deploy to Server

    steps:
      # Step 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main

      # Step 2. Install sshpass
      - name: Install sshpass
        run: |
          brew install sshpass
        shell: bash

      # Step 3. Deploy to Server
      - name: Deploy to Server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }} "rm -rf public_html/*"
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -r ./src/* ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }}:public_html/
        shell: bash
